# Form implementation generated from reading ui file 'e:\tzy\github\easytts\src\ui\sentence_display.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_sentenceDisplay(object):
    def setupUi(self, sentenceDisplay):
        sentenceDisplay.setObjectName("sentenceDisplay")
        sentenceDisplay.resize(749, 352)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(sentenceDisplay.sizePolicy().hasHeightForWidth())
        sentenceDisplay.setSizePolicy(sizePolicy)
        sentenceDisplay.setMinimumSize(QtCore.QSize(0, 150))
        sentenceDisplay.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(sentenceDisplay)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sentenceWidget = QtWidgets.QWidget(parent=sentenceDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sentenceWidget.sizePolicy().hasHeightForWidth())
        self.sentenceWidget.setSizePolicy(sizePolicy)
        self.sentenceWidget.setObjectName("sentenceWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sentenceWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sentenceTextBrowser = QtWidgets.QTextBrowser(parent=self.sentenceWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sentenceTextBrowser.sizePolicy().hasHeightForWidth())
        self.sentenceTextBrowser.setSizePolicy(sizePolicy)
        self.sentenceTextBrowser.setObjectName("sentenceTextBrowser")
        self.verticalLayout.addWidget(self.sentenceTextBrowser)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sentenceSetButton = QtWidgets.QPushButton(parent=self.sentenceWidget)
        self.sentenceSetButton.setObjectName("sentenceSetButton")
        self.horizontalLayout.addWidget(self.sentenceSetButton)
        self.label = QtWidgets.QLabel(parent=self.sentenceWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sentenceIdLabel = QtWidgets.QLabel(parent=self.sentenceWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sentenceIdLabel.sizePolicy().hasHeightForWidth())
        self.sentenceIdLabel.setSizePolicy(sizePolicy)
        self.sentenceIdLabel.setObjectName("sentenceIdLabel")
        self.horizontalLayout.addWidget(self.sentenceIdLabel)
        self.speakerLabel = QtWidgets.QLabel(parent=self.sentenceWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speakerLabel.sizePolicy().hasHeightForWidth())
        self.speakerLabel.setSizePolicy(sizePolicy)
        self.speakerLabel.setObjectName("speakerLabel")
        self.horizontalLayout.addWidget(self.speakerLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addWidget(self.sentenceWidget)
        self.sentencePlyer = AudioPlayer(parent=sentenceDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sentencePlyer.sizePolicy().hasHeightForWidth())
        self.sentencePlyer.setSizePolicy(sizePolicy)
        self.sentencePlyer.setMinimumSize(QtCore.QSize(250, 0))
        self.sentencePlyer.setMaximumSize(QtCore.QSize(250, 16777215))
        self.sentencePlyer.setObjectName("sentencePlyer")
        self.horizontalLayout_2.addWidget(self.sentencePlyer)

        self.retranslateUi(sentenceDisplay)
        QtCore.QMetaObject.connectSlotsByName(sentenceDisplay)

    def retranslateUi(self, sentenceDisplay):
        _translate = QtCore.QCoreApplication.translate
        sentenceDisplay.setWindowTitle(_translate("sentenceDisplay", "Form"))
        self.sentenceSetButton.setText(_translate("sentenceDisplay", "tts设置"))
        self.label.setText(_translate("sentenceDisplay", "句子id："))
        self.sentenceIdLabel.setText(_translate("sentenceDisplay", "TextLabel"))
        self.speakerLabel.setText(_translate("sentenceDisplay", "旁白"))
from src.audio_player import AudioPlayer
