# Form implementation generated from reading ui file 'e:\tzy\github\easytts\src\ui\tts_set_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TTSSetDialog(object):
    def setupUi(self, TTSSetDialog):
        TTSSetDialog.setObjectName("TTSSetDialog")
        TTSSetDialog.resize(650, 296)
        self.verticalLayout = QtWidgets.QVBoxLayout(TTSSetDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = TTSSet(parent=TTSSetDialog)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(TTSSetDialog)
        QtCore.QMetaObject.connectSlotsByName(TTSSetDialog)

    def retranslateUi(self, TTSSetDialog):
        _translate = QtCore.QCoreApplication.translate
        TTSSetDialog.setWindowTitle(_translate("TTSSetDialog", "Dialog"))
from src.tts_set import TTSSet
